### PR TITLE
SCSS linter readme.md recommendation

### PR DESCRIPTION
**Pull request by rickleegit**

### CODE REVIEW

**Comment by rickleegit** [comment]
What I added feels like it might be a little out of place in the readme, based on what you have in there. But not sure where else it would go.

**Comment by awong-dev** [comment]
yeah, I can't think of a better place to put it either.  Can you fix the PR title to be a full sentence without the abbreviation?

**Comment by awong-dev** [comment]
LGTM!

**Comment by emilyville** [comment]
2 thoughts here:
- I think this might make more sense in the roadrunner-rails repo since that's where the linter is. And we should also add the linter here, but currently it's not here and neither is any of that documentation. 
-  I think this change accidentally got blown away with a duplicate README / readme thing that happened in PR #59 

I can add it back, but I agree this is an odd place for it, especially given current lack of adherence in this repo... 

@awong-dev @webinista

**Pull request merged**
